version: '3.8'

services:
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:6.15
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 82
    ports:
     - "8082:82"
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: reverso
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"